### ISSUE TITLE
Tests are slow

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zdaemon#12]
The test suite takes over 60 seconds.

Two tests are especially slow:
- nonzero_exit_on_program_failure (zdaemon.tests.tests) (33.362 s)
- src/zdaemon/README.rst (10.386 s)

Some other tests are longer than 1 second:
- DAEMON_MANAGER_MODE_leak (zdaemon.tests.tests) (2.109 s)
- allow_duplicate_arguments (zdaemon.tests.tests) (2.327 s)
- dont_hang_when_program_doesnt_start (zdaemon.tests.tests) (2.138 s)
- make_sure_non_daemon_mode_doesnt_hang_when_program_exits (zdaemon.tests.tests) (1.237 s)
- test_start_test_program (zdaemon.tests.tests) (6.328 s)
- test_start_timeout (zdaemon.tests.tests) (3.311 s)
- test_stop_timeout (zdaemon.tests.tests) (3.550 s)

The rest are fast.

**Comment by mgedmin** [comment]
I have an amazing patch that shortens the test runtime to 14s, but it breaks one fragile test (dont_hang_when_program_doesnt_start), BECAUSE THAT TEST IS RACY.

**Comment by mgedmin** [comment]
dont_hang_when_program_doesnt_start relies on one of two possible sequence of events:

- get_status() reports that daemon manager is not running
- ./zdaemon spawns the daemon manager
- get_status() reports that daemon manager is running but the managed process is not
- get_status() reports that daemon manager is not running

or

- get_status() reports that daemon manager is not running
- ./zdaemon spawns the daemon manager
- get_status() reports that daemon manager is not running until 10 seconds elapse

The test, however, sets up a situation where

1. ./zdaemon spawns the daemon manager
2. the daemon manager spawns the process
3. the process exits with an error message ("sleep: missing operand")
4. go to step 2 until backoff-limit is reached (2 seconds)

If the get_status() check hits the window between 2 and 3, the main wait loop will assume the process started correctly and will exit.

Um.  I now see that I accidentally moved the time.sleep() inside an if where it should've stayed outside, which made the race easier to hit (and introduced a bug where the timeout was much too short).  Once I fixed that the test passes.

**Comment by mgedmin** [comment]
Ha ha no it doesn't.  The race is harder to hit, perhaps, but it's still possible.  And the test run time went from 14s to 40 :(.

**Comment by icemac** [comment]
@mgedmin Is this issue still valid or can it be closed? 

Currently the tests take about 80 s on Python 3.11 in GHA. So it does not seem to be faster than 8 years ago.

**Comment by mgedmin** [comment]
I have no plans to work on this, so I suppose it can be closed.
